### ISSUE TITLE
Blocking behaviour

### ISSUE THREAD

**Issue by melisgl** [joaotavora/hunchensocket#28]
Is there any way to guarantee that a call to send-text-message is not going to block? send-frame acquires a write lock, which suggests that it may be intended to be safely called from arbitrary threads, but if it can block, then it's not such a good idea and I should have a queue of messages to send which is processed by the thread that handles the websocket request.

**Comment by joaotavora** [comment]
Hi @melisgl, I'm a bit disconnected from this project at the moment.  I'd have to think a bit about that answer, but from a very cursory reading of the code, I assume it's the usual buffer problem.  If the output buffer is full then you're going to block.  But why wouldn't you want that? If you have a queue of people waiting to get messages out of a very thin straw, how can you want to "not block" exactly.  
I don't know if you need an explicit queue, why not have those threads all wait on the lock?  Or do you need the order?

**Comment by melisgl** [comment]
The scenario I had in mind involved many views (websocket clients here) of the same model which is updated in some main thread on the server (not the request thread). If send-text-message carrying the update was called from that main thread, then a single client that doesn't read its messages could block the main thread. This could be worked around by instead queuing said messages for the websocket request thread to read and send.

**Comment by joaotavora** [comment]
I can't understand this, sorry. I do believe if more than one thread wants to send message to a websocket interface then they will "queue" up on the lock.  The reason I put "queue" in quotes is that the order is not guaranteed.  I don't know your application, perhaps order does make a difference.  Anyway, I hope you've understanded the _reason_ why `send-frame` might block.  It's in case the buffer is full, which is the output buffer might be full.  

And speaking of that, I'm not so sure.  It seems I use `force-output` , which means it would *not* block.  Anyway, that's all I can offer for now.

**Comment by melisgl** [comment]
Thank you for confirming this.
