### ISSUE TITLE
Websocket server without hunchentoot?

### ISSUE THREAD

**Issue by snunez1** [joaotavora/hunchensocket#34]
Has anyone seen an example of, or know how to, use hunchensocket without hunchentoot? I'm looking for the lightest weight websocket server I can find (with a non-copyleft license) for interprocess communication.

Any ideas?

**Comment by joaotavora** [comment]
The hunchen is the socket, sorry. :-)   It's way too coupled to hunchentoot, I don't see any reasonable way to uncouple it except fork it and start over.
