### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [joaotavora/hunchensocket#40]
Building with SBCL 2.2.7.28-02bc916fd / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id e2384c971ac65a63fb910a061a3cdec4b684debb

*hunchensocket-tests* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: BASE64 is a nickname for the package CL-BASE64

```

*hunchensocket* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: BASE64 is a nickname for the package CL-BASE64

```

[Full log here](http://report.quicklisp.org/2022-10-31/failure-report/hunchensocket.html)

**Comment by hanshuebner** [comment]
@quicklisp Is this still an issue?

**Comment by quicklisp** [comment]
Not a problem any more.

**Comment by hanshuebner** [comment]
Thanks, Zach!
